FROM nginx:alpine
EXPOSE 80

RUN mkdir -p /usr/src/vendor

# COPY codes into image
COPY . /usr/src/vendor/

# install nodejs
RUN apk add nodejs npm
RUN npm i yarn -g

# set default workspace
WORKDIR /usr/src/vendor


# run codes and build product
RUN yarn add
RUN yarn build prod

RUN cp default.conf /etc/nginx/conf.d/
RUN cp -r build/* /usr/share/nginx/html/
